### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by agoodStu** [dmardanbeigi/Microsaccade-Toolbox-in-Python#1]
The type of eye tracker I use is Tobii. So the data file is different from yours. Can you tell me the meanings of 「RESOLUTION」and how to calculate it? By the way, about 「velocity」in data files, I have looked at 「EyeLink User's Manual」but couldn't find out the way to calculate it? Can you tell me something about it, too? Thanks a lot.

**Comment by DMardanbegi** [comment]
The resX and resY in the eyelink data are used to convert pixel values to degrees of visual angle. ResX is the amount of deg/pixel at the gaze point. So you can calculate that based on your geometry or you can use a fixed value for the entire screen if the screen size is not very large. For the velocity, they don't tell how exactly the velocity value is calculated but you can use your own method (e.g. Savitsky-Golay).

**Comment by agoodStu** [comment]
Thank you very much.
